#!/bin/bash

# Creează venv dacă nu există
python3 -m venv .venv

# Activează venv
source .venv/bin/activate

# Instalează din requirements.txt
pip install -r quickrequirements.txt

# Adaugă calea în PATH (foarte important pentru Jenkins)
export PATH="$PWD/.venv/bin:$PATH"
